#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Madrsa")]
	public partial class DataClasses : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserthafizbook(hafizbook instance);
    partial void Updatehafizbook(hafizbook instance);
    partial void Deletehafizbook(hafizbook instance);
    partial void InsertHifzstudent(Hifzstudent instance);
    partial void UpdateHifzstudent(Hifzstudent instance);
    partial void DeleteHifzstudent(Hifzstudent instance);
    #endregion
		
		public DataClasses() : 
				base(global::Edu.Properties.Settings.Default.MadrsaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<hafizbook> hafizbooks
		{
			get
			{
				return this.GetTable<hafizbook>();
			}
		}
		
		public System.Data.Linq.Table<Hifzstudent> Hifzstudents
		{
			get
			{
				return this.GetTable<Hifzstudent>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ddeletehafizbooldelete")]
		public int ddeletehafizbooldelete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> staffid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), staffid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.gethafizbook")]
		public ISingleResult<gethafizbookResult> gethafizbook()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<gethafizbookResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.inserthafizbook")]
		public int inserthafizbook([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatehafizbook")]
		public int updatehafizbook([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insserthafizstd")]
		public int insserthafizstd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fathername, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string admissioninbk, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nic, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nation, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> doa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string paddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, fathername, mobile, admissioninbk, nic, nation, doa, dob, address, paddress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.gethafizstudent")]
		public ISingleResult<gethafizstudentResult> gethafizstudent()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<gethafizstudentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.upddatethafizstd")]
		public int upddatethafizstd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fathername, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string admissioninbk, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nic, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nation, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> doa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string paddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, fathername, mobile, admissioninbk, nic, nation, doa, dob, address, paddress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ddeletehafizstuddentdelete")]
		public int ddeletehafizstuddentdelete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> staffid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), staffid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ddeletenazrabooldelete")]
		public int ddeletenazrabooldelete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> staffid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), staffid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ddeletenazrastuddentdelete")]
		public int ddeletenazrastuddentdelete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> staffid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), staffid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getnazrabook")]
		public ISingleResult<getnazrabookResult> getnazrabook()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getnazrabookResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertnazrabook")]
		public int insertnazrabook([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.inssertnazrastd")]
		public int inssertnazrastd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fathername, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string admissioninbk, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nic, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nation, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> doa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string paddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, fathername, mobile, admissioninbk, nic, nation, doa, dob, address, paddress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updatenazrabook")]
		public int updatenazrabook([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.upddatetnazrastd")]
		public int upddatetnazrastd([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fathername, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string admissioninbk, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nic, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="TinyInt")] System.Nullable<byte> nation, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> doa, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dob, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(150)")] string paddress)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, name, fathername, mobile, admissioninbk, nic, nation, doa, dob, address, paddress);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getnazrastudent")]
		public ISingleResult<getnazrastudentResult> getnazrastudent()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<getnazrastudentResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hafizbook")]
	public partial class hafizbook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _hafizbookdata;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnhafizbookdataChanging(string value);
    partial void OnhafizbookdataChanged();
    #endregion
		
		public hafizbook()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hafizbookdata", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string hafizbookdata
		{
			get
			{
				return this._hafizbookdata;
			}
			set
			{
				if ((this._hafizbookdata != value))
				{
					this.OnhafizbookdataChanging(value);
					this.SendPropertyChanging();
					this._hafizbookdata = value;
					this.SendPropertyChanged("hafizbookdata");
					this.OnhafizbookdataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hifzstudent")]
	public partial class Hifzstudent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idd;
		
		private string _name;
		
		private string _fathername;
		
		private string _mobileno;
		
		private int _admissioninbook;
		
		private int _nic;
		
		private byte _nation;
		
		private System.DateTime _doa;
		
		private System.DateTime _dob;
		
		private string _address;
		
		private string _paddress;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniddChanging(int value);
    partial void OniddChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnfathernameChanging(string value);
    partial void OnfathernameChanged();
    partial void OnmobilenoChanging(string value);
    partial void OnmobilenoChanged();
    partial void OnadmissioninbookChanging(int value);
    partial void OnadmissioninbookChanged();
    partial void OnnicChanging(int value);
    partial void OnnicChanged();
    partial void OnnationChanging(byte value);
    partial void OnnationChanged();
    partial void OndoaChanging(System.DateTime value);
    partial void OndoaChanged();
    partial void OndobChanging(System.DateTime value);
    partial void OndobChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnpaddressChanging(string value);
    partial void OnpaddressChanged();
    #endregion
		
		public Hifzstudent()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idd", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idd
		{
			get
			{
				return this._idd;
			}
			set
			{
				if ((this._idd != value))
				{
					this.OniddChanging(value);
					this.SendPropertyChanging();
					this._idd = value;
					this.SendPropertyChanged("idd");
					this.OniddChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fathername", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fathername
		{
			get
			{
				return this._fathername;
			}
			set
			{
				if ((this._fathername != value))
				{
					this.OnfathernameChanging(value);
					this.SendPropertyChanging();
					this._fathername = value;
					this.SendPropertyChanged("fathername");
					this.OnfathernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobileno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string mobileno
		{
			get
			{
				return this._mobileno;
			}
			set
			{
				if ((this._mobileno != value))
				{
					this.OnmobilenoChanging(value);
					this.SendPropertyChanging();
					this._mobileno = value;
					this.SendPropertyChanged("mobileno");
					this.OnmobilenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admissioninbook", DbType="Int NOT NULL")]
		public int admissioninbook
		{
			get
			{
				return this._admissioninbook;
			}
			set
			{
				if ((this._admissioninbook != value))
				{
					this.OnadmissioninbookChanging(value);
					this.SendPropertyChanging();
					this._admissioninbook = value;
					this.SendPropertyChanged("admissioninbook");
					this.OnadmissioninbookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nic", DbType="Int NOT NULL")]
		public int nic
		{
			get
			{
				return this._nic;
			}
			set
			{
				if ((this._nic != value))
				{
					this.OnnicChanging(value);
					this.SendPropertyChanging();
					this._nic = value;
					this.SendPropertyChanged("nic");
					this.OnnicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nation", DbType="TinyInt NOT NULL")]
		public byte nation
		{
			get
			{
				return this._nation;
			}
			set
			{
				if ((this._nation != value))
				{
					this.OnnationChanging(value);
					this.SendPropertyChanging();
					this._nation = value;
					this.SendPropertyChanged("nation");
					this.OnnationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doa", DbType="Date NOT NULL")]
		public System.DateTime doa
		{
			get
			{
				return this._doa;
			}
			set
			{
				if ((this._doa != value))
				{
					this.OndoaChanging(value);
					this.SendPropertyChanging();
					this._doa = value;
					this.SendPropertyChanged("doa");
					this.OndoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="Date NOT NULL")]
		public System.DateTime dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this.OndobChanging(value);
					this.SendPropertyChanging();
					this._dob = value;
					this.SendPropertyChanged("dob");
					this.OndobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paddress", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string paddress
		{
			get
			{
				return this._paddress;
			}
			set
			{
				if ((this._paddress != value))
				{
					this.OnpaddressChanging(value);
					this.SendPropertyChanging();
					this._paddress = value;
					this.SendPropertyChanged("paddress");
					this.OnpaddressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class gethafizbookResult
	{
		
		private int _SNO;
		
		private string _Name;
		
		public gethafizbookResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNO", DbType="Int NOT NULL")]
		public int SNO
		{
			get
			{
				return this._SNO;
			}
			set
			{
				if ((this._SNO != value))
				{
					this._SNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class gethafizstudentResult
	{
		
		private int _SNO;
		
		private string _Name;
		
		private string _fathername;
		
		private string _mobileno;
		
		private string _admissionno;
		
		private string _nation;
		
		private System.DateTime _doa;
		
		private int _cnic;
		
		private System.DateTime _dob;
		
		private string _adddress;
		
		private string _Paddress;
		
		public gethafizstudentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNO", DbType="Int NOT NULL")]
		public int SNO
		{
			get
			{
				return this._SNO;
			}
			set
			{
				if ((this._SNO != value))
				{
					this._SNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fathername", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fathername
		{
			get
			{
				return this._fathername;
			}
			set
			{
				if ((this._fathername != value))
				{
					this._fathername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobileno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string mobileno
		{
			get
			{
				return this._mobileno;
			}
			set
			{
				if ((this._mobileno != value))
				{
					this._mobileno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admissionno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string admissionno
		{
			get
			{
				return this._admissionno;
			}
			set
			{
				if ((this._admissionno != value))
				{
					this._admissionno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nation", DbType="VarChar(10)")]
		public string nation
		{
			get
			{
				return this._nation;
			}
			set
			{
				if ((this._nation != value))
				{
					this._nation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doa", DbType="Date NOT NULL")]
		public System.DateTime doa
		{
			get
			{
				return this._doa;
			}
			set
			{
				if ((this._doa != value))
				{
					this._doa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnic", DbType="Int NOT NULL")]
		public int cnic
		{
			get
			{
				return this._cnic;
			}
			set
			{
				if ((this._cnic != value))
				{
					this._cnic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="Date NOT NULL")]
		public System.DateTime dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this._dob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adddress", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string adddress
		{
			get
			{
				return this._adddress;
			}
			set
			{
				if ((this._adddress != value))
				{
					this._adddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paddress", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Paddress
		{
			get
			{
				return this._Paddress;
			}
			set
			{
				if ((this._Paddress != value))
				{
					this._Paddress = value;
				}
			}
		}
	}
	
	public partial class getnazrabookResult
	{
		
		private int _SNO;
		
		private string _Name;
		
		public getnazrabookResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNO", DbType="Int NOT NULL")]
		public int SNO
		{
			get
			{
				return this._SNO;
			}
			set
			{
				if ((this._SNO != value))
				{
					this._SNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class getnazrastudentResult
	{
		
		private int _SNO;
		
		private string _Name;
		
		private string _fathername;
		
		private string _mobileno;
		
		private string _admissionno;
		
		private string _nation;
		
		private System.DateTime _doa;
		
		private string _cnic;
		
		private System.DateTime _dob;
		
		private string _adddress;
		
		private string _Paddress;
		
		public getnazrastudentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SNO", DbType="Int NOT NULL")]
		public int SNO
		{
			get
			{
				return this._SNO;
			}
			set
			{
				if ((this._SNO != value))
				{
					this._SNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fathername", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fathername
		{
			get
			{
				return this._fathername;
			}
			set
			{
				if ((this._fathername != value))
				{
					this._fathername = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobileno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string mobileno
		{
			get
			{
				return this._mobileno;
			}
			set
			{
				if ((this._mobileno != value))
				{
					this._mobileno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admissionno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string admissionno
		{
			get
			{
				return this._admissionno;
			}
			set
			{
				if ((this._admissionno != value))
				{
					this._admissionno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nation", DbType="VarChar(10)")]
		public string nation
		{
			get
			{
				return this._nation;
			}
			set
			{
				if ((this._nation != value))
				{
					this._nation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doa", DbType="Date NOT NULL")]
		public System.DateTime doa
		{
			get
			{
				return this._doa;
			}
			set
			{
				if ((this._doa != value))
				{
					this._doa = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnic", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cnic
		{
			get
			{
				return this._cnic;
			}
			set
			{
				if ((this._cnic != value))
				{
					this._cnic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="Date NOT NULL")]
		public System.DateTime dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this._dob = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string adddress
		{
			get
			{
				return this._adddress;
			}
			set
			{
				if ((this._adddress != value))
				{
					this._adddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paddress", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Paddress
		{
			get
			{
				return this._Paddress;
			}
			set
			{
				if ((this._Paddress != value))
				{
					this._Paddress = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
